notifications:
  email: false

env:
  global:
    - TEST_DEPENDS="chompack"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: '2.7'
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: '3.6'
    - os: osx
      language: python
      env: PYVERSION=2.7
      language: generic
    - os: osx
      language: python
      env: PYVERSION=3.6
      language: generic

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install python-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask uninstall oclint; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;bash miniconda.sh -b -p $HOME/miniconda; export PATH="$HOME/miniconda/bin:$PATH" ;  fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then conda create -y -n myenv python=$PYVERSION && source $HOME/miniconda/bin/activate myenv; fi

install:
  - python setup.py -q install

script:
  - pip install $TEST_DEPENDS
  - python example.py
