notifications:
  email: false
os:
- linux
before_install:
- sudo apt-get install python-dev
- sudo apt-get install libblas-dev
- sudo apt-get install liblapack-dev
- sudo apt-get install libatlas-dev
- pip install git+https://github.com/cvxopt/cvxopt@dev
- pip install git+https://github.com/cvxopt/chompack@master
language: python
python:
- '2.7'
- '3.5'
install:
- python setup.py -q install
script:
- python example.py
deploy:
  provider: pypi
  user: msa
  password:
    secure: i09M0YIu6TxoxYdFQ/NbyTAtW5xb2itCo7kK8cZgCIg0nDbQBvFWYss67v4zfGLsi0yxL10osf48pAm9jQVU1MSGLdyBfoQ0F02WpptV+zDtLj7hgE3to5ksB5WQuqN7tXwctG2AQgxwQnm9i892U9Nb+KoCaP20MMviTqIBxkX3PJFHnwAWLX9JiGO87jFMSpTKtsekaBIm8fIujjY7Jelc+umOl7/v4XhWZWspvmuigpnq6ct6q2Llx1hQLNw1rfOE+cwgQg2n2W63Eih9aY2u/kiBxGmdRaDl9T0g8U7ftCv0Rum/CLjNhI/PCDdnNRhFyUTjZQm/8DKCrBOYmqAeTKqtQYEMXPSo1+N1dC/sd8YzVKfLzcrNSLPM90IbsK0W2LFo6gfawkdHV3Smoy/ub3mJC3ta6U/SwenVg9WxvtS48U4luKE/i/hydpkCHb/GAyEukEl5FivboBmpE8pFjGWozsyMPHso9rvdPg1GpDlGAz7U1B2zF6aCoqw9vl1t69WGV9X70d8PNrIhXHFriBPZtdV34OlO0L+zwE9d77j7DCjBerNky1DqRJZW+kqfPtFORpH3WiWowq/dIZzx8IEufzNioYDpLnQ+gMlh8VkMNNG5k4X2iTE+rOOpEVoHUXxtnIM0jee9Vra71n0E3Ktx4Ha68dppJO6KXxs=
  on:
    tags: true
    repo: cvxopt/smcp
