notifications:
  email: false
os:
- linux
before_install:
- sudo apt-get install python-dev libblas-dev liblapack-dev
- pip install chompack 
language: python
python:
- '2.7'
- '3.6'
install:
- python setup.py -q install
script:
- python example.py
