notifications:
  email: false
os:
- linux
before_install:
- sudo apt-get install python-dev
- sudo apt-get install libblas-dev
- sudo apt-get install liblapack-dev
- wget http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-4.5.3.tar.gz
- tar -xf SuiteSparse-4.5.3.tar.gz
- CVXOPT_SUITESPARSE_SRC_DIR=$(pwd)/SuiteSparse pip install cvxopt
- pip install chompack
language: python
python:
- '2.7'
- '3.5'
install:
- python setup.py -q install
script:
- python example.py
deploy:
  provider: pypi
  user: msa
  password:
    secure: bV3oHy9EuAh/7wsEwdN/oZnTfuBJTRqYhdCgg4U+C15a6MQFK73HqyjsHgQTqibtAPRd5+BQqxDqpM2SNIU1fp6HTXavIcslfOWAfFsAVTTlc/p9UcD3Bnu3Ot6shPv6tlaoLJ1+Grigg6EtOTQnvsaDSW689wWTTyYdqWYPXoaWvJwpoTQN7wN+cHUXcOqmuRpELeCp8DsTNvtsek0iCbhgbJgMVtP1bkPEfZkaPSxec9wDukmzpdIXRHvMqJUl1x9Fb9mnkFN7PxfiFZrR5wZFSPX56WYkC079rDho165RTj9Ag9eg/4HHXCAHyv83NPer9+29sLt9L4NIlKg0iooJ0KjftLB5CzZkGctEzR7/A0BrUr5sMTux49AEUYtoU3N1zNZsQ9ooqheQ6dWNIf9HPrCaojUi9OD1l8xFEKtyqHF9Wl/ArIRiriJlIy091BYpAQIhlhQIEcwfXcqm6+Q3Se40beSZPsc0dACIYuyIVK6CQQZqfTIw5jABL2geU8kKvn8LixNVuxq/PmdxMQIjJCm8p8dEHeReDNIKaqpi+h4baMiTSdnHLyKZe3fMXGEJrDxHkZNAOrGQVpBsd0ypNkHnQph5UakwO5nwiAGUzf7H2qLrodunrcQemp9bnoTyp/zbicI+ycKFHAqujJBG+UYjgS0a4smCI6NP6m0=
  on:
    branch: master
    tags: true
    distributions: sdist
    repo: cvxopt/smcp
